### ISSUE TITLE
Code Search example

### ISSUE THREAD

**Issue by mayur-khatri** [openai/openai-cookbook#224]
I am running the same example as https://github.com/openai/openai-cookbook/blob/main/examples/Code_search.ipynb, it is giving below error.

```
Traceback (most recent call last):
  File "code-semantic-search.py", line 29, in <module>
    print(search(db, query))
  File "code-semantic-search.py", line 11, in search
    db['similarities'] = db.code_embedding.apply(lambda x: cosine_similarity(x, query_embedding))
  File "/Users/chetan/PycharmProjects/word-embeddings/openai-code/lib/python3.8/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/Users/chetan/PycharmProjects/word-embeddings/openai-code/lib/python3.8/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "/Users/chetan/PycharmProjects/word-embeddings/openai-code/lib/python3.8/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "code-semantic-search.py", line 11, in <lambda>
    db['similarities'] = db.code_embedding.apply(lambda x: cosine_similarity(x, query_embedding))
  File "/Users/chetan/PycharmProjects/word-embeddings/openai-code/lib/python3.8/site-packages/openai/embeddings_utils.py", line 68, in cosine_similarity
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
  File "<__array_function__ internals>", line 200, in dot
numpy.core._exceptions.UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U34393'), dtype('<U23')) -> None
```

**Comment by ted-at-openai** [comment]
Could not reproduce, unfortunately. Maybe something got messed up in your stored embeddings?
