### ISSUE TITLE
report an error

### ISSUE THREAD

**Issue by Yx7777** [openai/openai-cookbook#388]
error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

**Comment by xMarkz** [comment]
Same. This is my full error output:

error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:645:11)
    at _res.setHeader (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\base-server.js:129:24)
    at sendJson (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\api-utils\node.js:195:9)
    at apiRes.json (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\api-utils\node.js:351:31)
    at handler (webpack-internal:///(api)/./src/pages/api/get-answer-from-files.ts:50:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.apiResolver (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\api-utils\node.js:363:9)    
    at async DevServer.runApi (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\next-server.js:488:9)
    at async Object.fn (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\next-server.js:750:37)
    at async Router.execute (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\dev\next-dev-server.js:741:20)   
    at async DevServer.handleRequest (C:\Users\marco\Downloads\openai-cookbook-main\apps\file-q-and-a\nextjs\node_modules\next\dist\server\base-server.js:322:20)
