### ISSUE TITLE
remove `html` from requirements.txt

### ISSUE THREAD

**Issue by D1skin** [openai/openai-cookbook#407]
`html.parser` (and `html`) are built-in libs and are not required to be installed. furthermore, when installing the deps in `requirements.txt` having `html` there causes an error. please remove the line

https://github.com/openai/openai-cookbook/blob/7d418b9bf2b5546b2e8e2e3e2a1813ec5d939540/apps/web-crawl-q-and-a/requirements.txt#L24

```commandline
❯ pip install html
Looking in indexes: https://pypi.org/simple, https://1tOG39-qk3jtU1L9S9a89QrDPMBc5s1hY:****@pypi.fury.io/authomize/
Collecting html
  Downloading html-1.16.tar.gz (7.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/diskin/OAI_crawl_test/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y30eo9xe/html/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y30eo9xe/html/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-y30eo9xe/html/pip-egg-info
         cwd: /tmp/pip-install-y30eo9xe/html/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools.depends import Require
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/depends.py", line 6, in <module>
        from .py33compat import Bytecode
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/py33compat.py", line 11, in <module>
        from setuptools.extern.six.moves import html_parser
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 92, in __get__
        result = self._resolve()
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 115, in _resolve
        return _import_module(self.mod)
      File "/home/diskin/OAI_crawl_test/venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 82, in _import_module
        __import__(name)
    ModuleNotFoundError: No module named 'html.parser'; 'html' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Darshan016** [comment]
removed.

**Comment by ted-at-openai** [comment]
Merged your patch.
